/*
 * Generated by Bluespec Compiler, version 2022.01 (build 066c7a8)
 * 
 * On Tue Oct 17 23:03:46 EDT 2023
 * 
 */

/* Generation options: */
#ifndef __mkTb_rca32_h__
#define __mkTb_rca32_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkTb_rca32 module */
class MOD_mkTb_rca32 : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt32> INST_cycle;
  MOD_Wire<tUInt8> INST_gen_advance;
  MOD_Reg<tUInt8> INST_gen_extraReg;
  MOD_Wire<tUInt8> INST_gen_gen_advance;
  MOD_Reg<tUInt32> INST_gen_gen_cycle;
  MOD_Reg<tUInt32> INST_gen_gen_val0_r;
  MOD_Reg<tUInt32> INST_gen_gen_val1_r;
  MOD_Reg<tUInt8> INST_in_a;
  MOD_Reg<tUInt8> INST_in_b;
  MOD_Reg<tUInt8> INST_in_cin;
 
 /* Constructor */
 public:
  MOD_mkTb_rca32(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
  tUInt32 DEF_val1_value__h479;
  tUInt32 DEF_val0_value__h443;
  tUInt32 DEF_x__h8925;
  tUInt8 DEF_carry__h2622;
  tUInt8 DEF_gen_gen_cycle_ULT_128___d6;
  tUInt8 DEF_NOT_gen_extraReg_0___d51;
 
 /* Rules */
 public:
  void RL_gen_gen_run();
  void RL_gen_run();
  void RL_test();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTb_rca32 &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTb_rca32 &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTb_rca32 &backing);
};

#endif /* ifndef __mkTb_rca32_h__ */
